GET http://localhost:8000/api/employees

HTTP/1.1 500  - Internal Server Error
host: localhost:8000
connection: close
x-powered-by: PHP/8.2.12
cache-control: no-cache, private
date: Wed, 16 Jul 2025 12:50:24 GMT
content-type: text/html; charset=UTF-8
access-control-allow-origin: *